### ISSUE TITLE
Issue when compiling

### ISSUE THREAD

**Issue by jobrien375** [DominikN/ESP32-to-ESP32#2]
Hello,

When I compile the code I get this error message at the end

exit status 1
invalid user-defined conversion from 'IPv6Address' to 'const char*' [-fpermissive]

in reference to this line

` client_tcp->connect(peerAddr, PORT);`

**Comment by DominikN** [comment]
Hi, just added a GitHub Actions workflow and everything is building fine. Please check once more and let me know about the results.
